version: '3.8' 

services:
  mongo:
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password1
    container_name: mongo
    image: mongo

  webapi:
    ports: 
      - 8080:80
    environment: 
      - MongoDbSettings:ConnectionString=mongodb://mongoadmin:password1@mongo:27017
    depends_on:
      - mongo
    image: webapi-mongo:v2
